- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 
      
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ namespace}}"
    context: "{{ k8s_context }}"
    api_version: v1
    kind: Namespace
    state: present 