- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 
      
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: tst
    #context: "{{ k8s_context }}"
    context: kubernetes-admin@lab1.local
    api_version: v1
    kind: Namespace
    state: present